application: delicious-export
version: 3
runtime: python
api_version: 1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /index.html
  static_files: static/index.html
  upload: static/index.html

- url: /json.html
  static_files: static/json.html
  upload: static/json.html

- url: /main.js
  static_files: static/main.js
  upload: static/main.js

- url: .*
  script: main.py

builtins:
- appstats: on
